Repository openshift/kubefed, pull requests merged in 2019-07, with the labels that each got.

#8 Add a new spec file for building rpm images of kubefedctl
  kubefedctl.spec
Labels: approved, lgtm, size/L

#10 Update make target in the spec file.
  kubefedctl.spec
Labels: approved, lgtm, size/XS

#11 Add kubefedctl binary target in Makefile.ci
  kubefedctl.spec
  openshift/Makefile.ci
Labels: approved, lgtm, size/M

#14 Remove podman build command
  openshift/Makefile.ci
Labels: approved, lgtm, size/XS

#15 Makefile changes for kubefedctl client
  kubefedctl.spec
  openshift/Makefile.ci
Labels: approved, lgtm, size/M

#18 Minor changes in .spec file
  kubefedctl.spec
Labels: approved, lgtm, size/S
