Repository openshift/kubefed, pull requests merged in 2019-08, with the labels that each got.

#19 Fix downstream image builds for multi-arch
  Dockerfile
Labels: approved, lgtm, size/XS

#21 Dockerfile fix for copying the actual file rather than just the soft link.
  Dockerfile
Labels: approved, lgtm, size/XS

#23 Fix kubefedctl-client spec file
  kubefedctl.spec
Labels: approved, lgtm, size/XS

#20 Fast forward kubefed to rc5
  CHANGELOG.md
  cmd/controller-manager/app/controller-manager.go
  pkg/apis/core/v1beta1/validation/validation.go
  pkg/apis/core/v1beta1/validation/validation_test.go
  pkg/controller/sync/accessor.go
  pkg/controller/sync/status/status.go
  pkg/controller/webhook/federatedtypeconfig/webhook.go
  pkg/controller/webhook/kubefedcluster/webhook.go
  pkg/controller/webhook/kubefedconfig/webhook.go
  pkg/controller/webhook/util.go
  pkg/kubefedctl/enable/enable.go
  pkg/kubefedctl/join.go
  pkg/kubefedctl/options/options.go
  scripts/create-clusters.sh
  scripts/download-e2e-binaries.sh
  scripts/fix-ca-for-k3s.sh
  test/e2e/validation.go
Labels: approved, lgtm, size/L

#24 Pass the GIT env vars to make for downstream builds
  Dockerfile
Labels: approved, lgtm, size/XS

#26 Address image builder COPY idiosyncrasy
  Dockerfile
Labels: approved, lgtm, size/XS

#27 Change the target dir and create user and group called hyperfed in the Dockerfile
  Dockerfile
Labels: approved, lgtm, size/S
